
export const questionsBasic = [
    {
        id: 1,
        question: "How old are you?",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: null,
        answer: null
    },
    {
        id: 2,
        question: "Are you a man?",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: null,
        answer: null
    },
    {
        id: 3,
        question: "Are you a woman?",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: null,
        answer: null
    },
    {
        id: 6,
        question: "Are you interested in woman?",
        open: false,
        cubeText: "I love woman",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes"
    },
    {
        id: 7,
        question: "Are you interested in men?",
        open: false,
        cubeText: "I love men",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null
    }
]


    export const questionsAndAnswers = [
    {
        id: 8,
        question: "Do you enjoy multiple sex partners?",
        open: false,
        cubeText: "sex machine",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 9,
        question: "Do you say no to one night stands",
        open: false,
        cubeText: "No go to one nights",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {
        id: 10,
        question: "Are you looking for your soulmate here?",
        open: false,
        cubeText: "Looking for my soulmate",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {
        id: 11,
        question: "I am just because I am curious",
        open: false,
        cubeText: "Just curious",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {
        id: 12,
        question: "Are you a modern man?",
        open: false,
        cubeText: "Modern man",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 13,
        question: "Take a picture of your bag",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 14,
        question: "Do you use facial creme",
        open: false,
        cubeText: "I use facial creme",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 15,
        question: "Are you a vegan?",
        open: false,
        cubeText: "Vegan",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 16,
        question: "Are you a gentleman?",
        open: false,
        cubeText: "Gentleman",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {
        id: 17,
        question: "Take a photo of something on your wall",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: "https://hr-boesen.github.io/Front-end-2/dating-app-test/IMG_2455.JPG",
        answer: "yes",
        editMode: false
    },
    {
        id: 18,
        question: "Do you pay when you invite a girl out",
        open: false,
        cubeText: "Gentleman",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 19,
        question: "Are you a handy man?",
        open: false,
        cubeText: "handy man",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 20,
        question: "Do you eat meat?",
        open: false,
        cubeText: "Meat lover",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 21,
        question: "Take a photo of your head phones",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: "https://hr-boesen.github.io/Front-end-2/dating-app-test/IMG_2454.JPG",
        answer: "yes",
        editMode: false
    },
    {
        id: 22,
        question: "Do you have a lot body hair",
        open: false,
        cubeText: "Extra body hairy",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 23,
        question: "Do you have normal body hair",
        open: false,
        cubeText: "Normal body hair",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {
        id: 24,
        question: "I do NOT have a lot of body hair",
        open: false,
        cubeText: "Normal body hair",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {   id: 25,
        question: "Is your shoe size under or equal to size 43",
        open: false,
        cubeText: "Small feeds",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 26,
        question: "My favorite shoes are snearkers",
        open: false,
        cubeText: "Wear sneakers",
        likes: null,
        color: "black",
        imgURL: null,
        answer: null,
        editMode: false
    },
    {
        id: 27,
        question: "My favorite shoes are sandels",
        open: false,
        cubeText: "Love sandels",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 28,
        question: "My favorite shoes are leather shoes",
        open: false,
        cubeText: "Leather shoe kind of guy",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id: 29,
        question: "Take a photo of your shoes",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: "https://hr-boesen.github.io/Front-end-2/dating-app-test/IMG_2453.JPG",
        answer: "yes",
        editMode: false
    },
    {
        id: 30,
        question: "Do you skate?",
        open: false,
        cubeText: "Skater",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:31,
        question: "Did you skate?",
        open: false,
        cubeText: "Former skater!",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:32,
        question: "Have you ever run a mathon",
        open: false,
        cubeText: "Completed a marathon",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:33,
        question: "Are you a outdoor sporty type",
        open: false,
        cubeText: "Outdoor sporty",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:34,
        question: "Do you play any team sport",
        open: false,
        cubeText: "Team sport man",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:35,
        question: "Are you moms boy",
        open: false,
        cubeText: "moms boy",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:36,
        question: "Are you dads boy",
        open: false,
        cubeText: "Dads boy",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:37,
        question: "Are you a lonely child",
        open: false,
        cubeText: "lonely child",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:38,
        question: "Are you a bigbrother",
        open: false,
        cubeText: "Bigbrother",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:39,
        question: "Are you a little brother",
        open: false,
        cubeText: "littler brother",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:40,
        question: "Do you have many good friends",
        open: false,
        cubeText: "Many good friends",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:41,
        question: "Do you have a few good friends",
        open: false,
        cubeText: "A few good friends",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:42,
        question: "Take a picture of your bag",
        open: false,
        cubeText: null,
        likes: null,
        color: "black",
        imgURL: "https://hr-boesen.github.io/Front-end-2/dating-app-test/IMG_2456.JPG",
        answer: "yes",
        editMode: false
    },
    {
        id:43,
        question: "Do you have a BMI under 25",
        open: false,
        cubeText: "BMI under 25",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:44,
        question: "Do you have a BMI under 22",
        open: false,
        cubeText: "BMI under 22",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:45,
        question: "Are you a fan of the 80's",
        open: false,
        cubeText: "80's fan",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:46,
        question: "Are you a fan of the 90's ",
        open: false,
        cubeText: "90's fan",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:47,
        question: "Are you fan of pop culture",
        open: false,
        cubeText: "Love pop culture",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:48,
        question: "Do you have an overaverage income",
        open: false,
        cubeText: "Well payed job",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:49,
        question: "Do you have a high income",
        open: false,
        cubeText: "high income",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    {
        id:50,
        question: "Do you have a higher education",
        open: false,
        cubeText: "high educated",
        likes: null,
        color: "black",
        imgURL: null,
        answer: "yes",
        editMode: false
    },
    
 ]